-- Auto-generated from Data dictionary Excel files
-- Compatible with PostgreSQL 14+ and Supabase

CREATE SCHEMA IF NOT EXISTS bis_raw;
CREATE SCHEMA IF NOT EXISTS dmart_mp;
CREATE SCHEMA IF NOT EXISTS ump_raw;
CREATE SCHEMA IF NOT EXISTS app_auth;

DROP TABLE IF EXISTS ump_raw.user_master_ump CASCADE;
CREATE TABLE ump_raw.user_master_ump (
  id_pk bigint PRIMARY KEY,
  user_id bigint,
  user_name numeric,
  email_id text,
  mobile_number text,
  user_gender text,
  user_state_code text,
  csc_id text,
  active_status text,
  user_dtl_id text,
  entity_id text,
  entity_name text,
  entity_description text,
  entity_state_code text,
  status text,
  role_status text,
  role_id text,
  app_id text,
  app_description text,
  app_name text,
  app_status text,
  role_name text
);

DROP TABLE IF EXISTS bis_raw.t_bis_beneficiary_dtls CASCADE;
CREATE TABLE bis_raw.t_bis_beneficiary_dtls (
  id_pk bigint PRIMARY KEY,
  ben_id text,
  family_id text,
  member_id text,
  bis_family_id text,
  bis_member_id text,
  ben_ref_id text,
  state_cd text,
  dist_cd text,
  block_id text,
  village_id text,
  rural_urban_flag text,
  house_no text,
  pincode text,
  address text,
  dist_name text,
  state_name text,
  ben_mobile_no text,
  ben_email_id text,
  json_obj_ben_source_dtl text,
  json_obj_ben_ekyc_dtl text,
  obj_aadhar_vault text,
  active_status smallint,
  enrl_status text,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  abha_id text,
  payer_id bigint,
  tpa_isa_id bigint,
  json_obj_ben_othr_dtl text,
  src_flag text,
  aadhaar_no text,
  enrol_status bigint,
  entity_id text,
  card_no text,
  photo text,
  relation text,
  auth_mode text,
  primary_auth_mode text,
  new_member_flag text,
  gender text,
  year_of_birth text,
  name text,
  father_name text,
  age text,
  primary_ben_id text,
  approve_date timestamptz,
  enrol_date timestamptz,
  card_status text,
  aadhar_status text,
  reject_date timestamptz,
  date_of_birth text,
  scheme_code text,
  request_type text,
  auth_txn text,
  primary_auth_txn text,
  request_agent text,
  match_score text,
  source_type text,
  aadhaar_disp_code text,
  yob_secc text
);

DROP TABLE IF EXISTS dmart_mp.t_workflow_transaction_audit CASCADE;
CREATE TABLE dmart_mp.t_workflow_transaction_audit (
  work_id_pk bigint PRIMARY KEY,
  workflow_transaction_id bigint,
  status_id numeric,
  service_request_type text,
  json_object text,
  workflow_process_code text,
  remarks text,
  criteria_code text,
  workflow_id text,
  previous_workflow_role text,
  acted_workflow_user text,
  version text,
  final_level smallint,
  cluster_id bigint,
  active_flag smallint,
  transaction_dt timestamptz,
  verified text,
  time_taken_by_user numeric,
  time_taken_at_level numeric,
  current_entity_id text,
  current_tpa_group text,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  hist_created_by text,
  hist_created_dt timestamptz,
  check_list_json text,
  is_migrated text,
  reason_desc text,
  reason_id text,
  priority integer
);

DROP TABLE IF EXISTS dmart_mp.claim_paid_excel_t CASCADE;
CREATE TABLE dmart_mp.claim_paid_excel_t (
  id_pk bigserial PRIMARY KEY,
  registration_id text,
  case_id text,
  member_id text,
  family_id text,
  patient_name text,
  patient_dob text,
  patient_state_code smallint,
  patient_district_code smallint,
  patient_district_name text,
  patient_state_name text,
  gender text,
  age numeric,
  policy_code text,
  renewal_code text,
  category_details text,
  speciality_code text,
  procedure_details text,
  procedure_code text,
  case_type text,
  status_id_pk integer,
  case_status text,
  hospital_code text,
  hospital_name text,
  hosp_district_name text,
  hosp_state_name text,
  hospital_state_cd smallint,
  hospital_district_cd smallint,
  hosp_pan_number text,
  hospital_type text,
  admission_dt timestamptz,
  preauth_init_date timestamptz,
  amount_preauth_initiated numeric,
  preauth_approved_date timestamptz,
  amount_preauth_approved numeric,
  preauth_rejected_date timestamptz,
  surgery_dt timestamptz,
  death_dt timestamptz,
  discharge_dt timestamptz,
  claim_init_date timestamptz,
  amount_claim_initiated numeric,
  amount_claim_approved numeric,
  amount_claim_paid numeric,
  claim_rejected_date timestamptz,
  rf_amount numeric,
  tds_amount numeric,
  utr_no text,
  payment_paid_dt timestamptz,
  transaction_amount numeric,
  cpd_approved_date timestamptz,
  cpd_approved_amount numeric,
  cpd_user text,
  aco_approved_date timestamptz,
  aco_approved_amount numeric,
  aco_user text,
  sha_approved_date timestamptz,
  sha_approved_amount numeric,
  sha_user text,
  json_object_perauth text,
  json_object_claim text,
  json_object_ben text,
  last_insert_dt timestamptz,
  src_account_no text,
  src_ifsc_code text,
  paid_flag text,
  hosp_account_number text,
  ben_ifsc_code text,
  current_workflow_role text,
  current_workflow_user text,
  service_request_type text,
  m_flag integer,
  careplan_desc text,
  discharge_type text,
  admission_type text,
  claim_approved_date timestamptz,
  preauth_tat bigint,
  claim_tat bigint,
  payment_tat bigint,
  patient_mobile_number text
);

DROP TABLE IF EXISTS dmart_mp.workflow_users_t CASCADE;
CREATE TABLE dmart_mp.workflow_users_t (
  table_name text,
  id_pk bigint PRIMARY KEY,
  registration_id text,
  workflow_role text,
  status_id numeric,
  status_descrption text,
  workflow_process_code text,
  workflow_user text,
  created_dt timestamptz,
  last_action_dt timestamptz,
  initiated_amount numeric,
  approved_amount numeric,
  transaction_dt timestamptz,
  final_level smallint,
  active_flag smallint,
  created_by text,
  remarks text,
  json_object text,
  patient_state_code smallint,
  patient_district_code smallint,
  patient_state_name text,
  patient_district_name text,
  hospital_code text,
  hospital_name text,
  hospital_state_cd smallint,
  hospital_district_cd smallint,
  hosp_district_name text,
  hosp_state_name text,
  hospital_type text,
  mobile_number bigint,
  user_id text,
  user_name text,
  last_insert_dt timestamptz,
  m_flag integer,
  dashboard_workflow_role text,
  pendency_age text,
  ppd_tat text,
  overall_tat text
);

DROP TABLE IF EXISTS ump_raw.ump_user_dtl CASCADE;
CREATE TABLE ump_raw.ump_user_dtl (
  id_pk bigint PRIMARY KEY,
  active_yn smallint,
  obj_aadhar_vault text,
  created_by text,
  created_dt timestamptz,
  email_id text,
  last_login_time timestamptz,
  lock_yn smallint,
  mobile_number bigint,
  updated_by text,
  updated_dt timestamptz,
  user_age smallint,
  user_gender text,
  user_id text,
  user_name text,
  user_state_code smallint,
  user_dob text,
  reference_id text,
  default_authmode integer,
  failed_attempts integer,
  present_address text,
  aadhaar_address text,
  language text,
  user_enrollment text,
  user_designation text,
  otp_failed_updation timestamptz,
  otp_failed_count integer,
  aadhaar_display_code text,
  ekyc_flag text,
  csc_id text
);

DROP TABLE IF EXISTS dmart_mp.ump_role_dtl CASCADE;
CREATE TABLE dmart_mp.ump_role_dtl (
  id_pk bigserial PRIMARY KEY,
  role_id integer,
  created_by text,
  created_dt timestamptz,
  role_description text,
  role_name text,
  updated_by text,
  updated_dt timestamptz,
  workflow_applicable smallint,
  status text
);

DROP TABLE IF EXISTS dmart_mp.t_suspicious_api_case_data CASCADE;
CREATE TABLE dmart_mp.t_suspicious_api_case_data (
  suspicion_id bigserial PRIMARY KEY,
  reference_number text,
  application_type text,
  entity_type text,
  entity_id text,
  hospital_name text,
  division_name text,
  district_name text,
  state_lgd_code text,
  fraud_type text,
  investigation_status text,
  amount_risk numeric,
  amount_recovered numeric,
  investigator text,
  lst_trigger_event_date timestamptz,
  crt_date timestamptz DEFAULT now(),
  updt_date timestamptz
);

DROP TABLE IF EXISTS dmart_mp.t_suspicious_api_case_dtls CASCADE;
CREATE TABLE dmart_mp.t_suspicious_api_case_dtls (
  id_pk bigserial PRIMARY KEY,
  state_lgd_code text,
  reference_number text,
  application_type text,
  vendor_id text,
  trigger_type text,
  trigger_code text,
  trigger_time timestamptz,
  trigger_reason text,
  crt_date timestamptz DEFAULT now(),
  crt_usr text,
  flag text,
  district_name text
);

DROP TABLE IF EXISTS dmart_mp.hospital_master CASCADE;
CREATE TABLE dmart_mp.hospital_master (
  id_pk bigserial PRIMARY KEY,
  hospital_code text,
  facility_id text,
  hospital_name text,
  hospital_type text,
  district_name text,
  division_name text,
  hosp_spec_type text,
  nabh_certified text,
  enrl_status text,
  active_status text,
  accreditation_status text,
  empaneled_date date,
  deempanel_status text,
  pgdnb_status text,
  bed_capacity integer
);

DROP TABLE IF EXISTS app_auth.dashboard_users CASCADE;
CREATE TABLE app_auth.dashboard_users (
  id serial PRIMARY KEY,
  username text UNIQUE NOT NULL,
  password_hash text NOT NULL,
  full_name text NOT NULL,
  role text NOT NULL,
  department text,
  active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE OR REPLACE VIEW dmart_mp.claim_paid_t AS SELECT * FROM dmart_mp.claim_paid_excel_t;

CREATE INDEX IF NOT EXISTS idx_claim_district ON dmart_mp.claim_paid_excel_t (hosp_district_name);
CREATE INDEX IF NOT EXISTS idx_claim_status ON dmart_mp.claim_paid_excel_t (case_status);
CREATE INDEX IF NOT EXISTS idx_ben_dist ON bis_raw.t_bis_beneficiary_dtls (dist_name);
CREATE INDEX IF NOT EXISTS idx_fraud_ref ON dmart_mp.t_suspicious_api_case_dtls (reference_number);
CREATE INDEX IF NOT EXISTS idx_workflow_user ON dmart_mp.workflow_users_t (workflow_user);