-- Auto-generated from database_documentation.docx (28 dmart_mp tables)
-- Run after 001_init_schemas.sql

CREATE SCHEMA IF NOT EXISTS dmart_mp;

DROP TABLE IF EXISTS dmart_mp.claim_paid_t_portability CASCADE;
CREATE TABLE dmart_mp.claim_paid_t_portability (
  registration_id text,
  case_id text,
  member_id text,
  family_id text,
  patient_name text,
  patient_dob text,
  patient_state_code smallint,
  patient_district_code smallint,
  patient_district_name text,
  patient_state_name text,
  gender text,
  age numeric,
  policy_code text,
  renewal_code text,
  category_details text,
  speciality_code text,
  procedure_details text,
  procedure_code text,
  case_type text,
  status_id_pk integer,
  case_status text,
  hospital_code text,
  hospital_name text,
  hosp_district_name text,
  hosp_state_name text,
  hospital_state_cd smallint,
  hospital_district_cd smallint,
  hosp_pan_number text,
  hospital_type text,
  admission_dt timestamptz,
  preauth_init_date timestamptz,
  amount_preauth_initiated numeric,
  preauth_approved_date timestamptz,
  amount_preauth_approved numeric,
  preauth_rejected_date timestamptz,
  surgery_dt timestamptz,
  death_dt timestamptz,
  discharge_dt timestamptz,
  claim_init_date timestamptz,
  amount_claim_initiated numeric,
  amount_claim_approved numeric,
  amount_claim_paid numeric,
  claim_rejected_date timestamptz,
  rf_amount numeric,
  tds_amount numeric,
  utr_no text,
  payment_paid_dt timestamptz,
  transaction_amount numeric,
  cpd_approved_date timestamptz,
  cpd_approved_amount numeric,
  cpd_user text,
  aco_approved_date timestamptz,
  aco_approved_amount numeric,
  aco_user text,
  sha_approved_date timestamptz,
  sha_approved_amount numeric,
  sha_user text,
  json_object_perauth text,
  json_object_claim text,
  json_object_ben text,
  src_account_no text,
  src_ifsc_code text,
  paid_flag text,
  hosp_account_number text,
  ben_ifsc_code text,
  current_workflow_role text,
  current_workflow_user text,
  service_request_type text,
  m_flag integer,
  careplan_desc text,
  discharge_type text,
  admission_type text,
  claim_approved_date timestamptz,
  last_insert_dt timestamptz
);

DROP TABLE IF EXISTS dmart_mp.hospital_master_with_quality_certification CASCADE;
CREATE TABLE dmart_mp.hospital_master_with_quality_certification (
  hosp_state smallint,
  hosp_dist smallint,
  hospital_type text,
  hosp_id integer,
  facility_id text,
  hosp_name text,
  hosp_request_date timestamptz,
  hosp_empaneled_date timestamptz,
  hosp_spec_type text,
  hosp_spec_desc text,
  enrl_status integer,
  active_status integer,
  deempanel_status integer,
  hosp_status integer,
  hosp_status_desc text,
  bed_size integer,
  app_status integer,
  accreditation_status text,
  accred_id text,
  quality_certification text,
  m_flag text
);

DROP TABLE IF EXISTS dmart_mp.hospital_master_with_quality_certification_final CASCADE;
CREATE TABLE dmart_mp.hospital_master_with_quality_certification_final (
  hosp_id integer,
  facility_id text,
  hosp_name text,
  hem_speciality text,
  hosp_state smallint,
  state_name text,
  hospital_type text,
  hosp_dist smallint,
  hosp_request_date timestamptz,
  hosp_empaneled_date timestamptz,
  hosp_spec_type text,
  enrl_status integer,
  active_status integer,
  deempanel_status integer,
  hosp_status integer,
  hosp_status_desc text,
  bed_size integer,
  app_status integer,
  accreditation_status text,
  accred_id text,
  quality_certification text,
  m_flag text,
  hosp_city text,
  hosp_email_id text,
  hosp_mobile_no bigint,
  hosp_contact_no text,
  hosp_address text,
  hosp_pan_number text,
  account_number text,
  ifsc text,
  hosp_longitude text,
  hosp_latitude text,
  speciality_code text,
  speciality text,
  district_name text,
  hospital_subtype text
);

DROP TABLE IF EXISTS dmart_mp.icd_data_doctor_details CASCADE;
CREATE TABLE dmart_mp.icd_data_doctor_details (
  registration_id text,
  case_id text,
  id bigint,
  code text,
  display text,
  type text,
  typedescription text,
  idpk text,
  patient_state_code smallint
);

DROP TABLE IF EXISTS dmart_mp.lms_user_course_completion_status CASCADE;
CREATE TABLE dmart_mp.lms_user_course_completion_status (
  userid bigint,
  username text,
  firstname text,
  lastname text,
  phone2 text,
  email text,
  ab_pmjay_status text,
  ab_pmjay_completed_epoch bigint,
  ab_pmjay_completed_at_utc timestamptz,
  abdm_status text,
  abdm_completed_epoch bigint,
  abdm_completed_at_utc timestamptz,
  parententity text,
  entitytype text,
  selfentity text,
  role text
);

DROP TABLE IF EXISTS dmart_mp.m_lookup CASCADE;
CREATE TABLE dmart_mp.m_lookup (
  id_pk bigserial PRIMARY KEY,
  lookup_cd text,
  lookup_value text,
  active_yn smallint,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  type text
);

DROP TABLE IF EXISTS dmart_mp.m_source_data CASCADE;
CREATE TABLE dmart_mp.m_source_data (
  id_pk bigserial PRIMARY KEY,
  src_family_id text,
  state_cd text,
  dist_cd text,
  name text,
  age smallint,
  gender text,
  relation text,
  father_guardian_name text,
  dob text,
  rural_urban_flag text,
  block_or_town text,
  ward_or_village text,
  sub_division text,
  addr1 text,
  addr2 text,
  mobilenumber text,
  source_type text,
  enrl_status text,
  created_by text,
  created_dt timestamptz,
  bis_source text,
  village_ward_lgd_code text,
  mandal_taluka_lgd_code text,
  card_status text,
  bis_member_id text,
  card_no text,
  bis_family_id text,
  src_member_id text,
  state_scheme_family_id text,
  nfsa_card_type text,
  api_yn text,
  updated_by text,
  updated_dt timestamptz,
  nfsa_type text,
  scheme text
);

DROP TABLE IF EXISTS dmart_mp.payment_dtls CASCADE;
CREATE TABLE dmart_mp.payment_dtls (
  case_id text,
  payment_type text,
  bank_name text,
  payment_unique_id text,
  careplan_id text,
  src_account_no text,
  src_ifsc_code text,
  transaction_amount numeric,
  transaction_dt timestamptz,
  upload_file_name text,
  paid_flag text,
  payment_paid_dt timestamptz,
  paid_remarks text,
  payment_remarks text,
  state_code text,
  payer_id text,
  reject_code text,
  reject_flag text,
  reject_remarks text,
  payment_reject_dt timestamptz
);

DROP TABLE IF EXISTS dmart_mp.pro_workflow_users_t CASCADE;
CREATE TABLE dmart_mp.pro_workflow_users_t (
  table_name text,
  id_pk bigserial PRIMARY KEY,
  registration_id text,
  workflow_role text,
  status_id numeric,
  status_descrption text,
  workflow_process_code text,
  workflow_user text,
  created_dt timestamptz,
  last_action_dt timestamptz,
  initiated_amount numeric,
  approved_amount numeric,
  transaction_dt timestamptz,
  final_level smallint,
  active_flag smallint,
  created_by text,
  remarks text,
  json_object text,
  patient_state_code smallint,
  patient_district_code smallint,
  patient_state_name text,
  patient_district_name text,
  hospital_code text,
  hospital_name text,
  hospital_state_cd smallint,
  hospital_district_cd smallint,
  hosp_district_name text,
  hosp_state_name text,
  hospital_type text,
  mobile_number bigint,
  user_id text,
  user_name text,
  last_insert_dt timestamptz,
  m_flag integer,
  dashboard_workflow_role text,
  pendency_age text,
  ppd_tat text,
  overall_tat text,
  service_request_type text
);

DROP TABLE IF EXISTS dmart_mp.t_bis_beneficiary_disabled CASCADE;
CREATE TABLE dmart_mp.t_bis_beneficiary_disabled (
  state_cd text,
  card_no text,
  aadhaar_no text,
  card_status text,
  family_id text,
  member_id text,
  source_type text,
  name text,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  date_of_birth text,
  acted_workflow_user text,
  disabled_date timestamptz,
  reason_desc text,
  reason_id text
);

DROP TABLE IF EXISTS dmart_mp.t_bis_beneficiary_dtls CASCADE;
CREATE TABLE dmart_mp.t_bis_beneficiary_dtls (
  id_pk bigserial PRIMARY KEY,
  ben_id text,
  family_id text,
  member_id text,
  bis_family_id text,
  bis_member_id text,
  ben_ref_id text,
  state_cd text,
  dist_cd text,
  block_id text,
  village_id text,
  rural_urban_flag text,
  house_no text,
  pincode text,
  address text,
  dist_name text,
  state_name text,
  ben_mobile_no text,
  ben_email_id text,
  json_obj_ben_source_dtl text,
  json_obj_ben_ekyc_dtl text,
  active_status smallint,
  enrl_status text,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  abha_id text,
  payer_id bigint,
  tpa_isa_id bigint,
  json_obj_ben_othr_dtl text,
  src_flag text,
  enrol_status bigint,
  entity_id text,
  card_no text,
  photo text,
  relation text,
  auth_mode text,
  primary_auth_mode text,
  new_member_flag text,
  gender text,
  year_of_birth text,
  name text,
  father_name text,
  age text,
  primary_ben_id text,
  approve_date timestamptz,
  enrol_date timestamptz,
  card_status text,
  aadhar_status text,
  reject_date timestamptz,
  date_of_birth text,
  scheme_code text,
  request_type text,
  auth_txn text,
  primary_auth_txn text,
  request_agent text,
  match_score text,
  source_type text,
  aadhaar_disp_code text
);

DROP TABLE IF EXISTS dmart_mp.t_card_printing_status CASCADE;
CREATE TABLE dmart_mp.t_card_printing_status (
  card_no text,
  entity_id text,
  batch_id text,
  user_id text,
  state_cd text,
  district_cd text,
  subdistrict_town text,
  village_ward text,
  urban_or_rural text,
  card_name text,
  card_fathername text,
  card_relation text,
  card_yob text,
  card_gender text,
  card_address text,
  abha_no text,
  card_photo text,
  card_print_status text,
  enroll_date timestamptz,
  approve_date timestamptz,
  card_gen_date timestamptz,
  card_print_date timestamptz,
  card_distribute_date timestamptz,
  card_deliver_date timestamptz,
  ben_id text,
  family_id text,
  age text,
  source_type text,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  mobile_number text,
  operator_id text,
  operator_name text,
  operator_contact text,
  state_name text,
  district_name text,
  sub_district_name text,
  village_name text
);

DROP TABLE IF EXISTS dmart_mp.t_deempanelment_details CASCADE;
CREATE TABLE dmart_mp.t_deempanelment_details (
  id_pk bigserial PRIMARY KEY,
  hosp_id integer,
  status integer,
  end_date timestamptz,
  start_date timestamptz,
  app_status integer,
  stop_payment text,
  remarks text,
  attachment text,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  type text,
  reasons text,
  deempanel_scheme text,
  deempanel_speclity text,
  due_date timestamptz,
  documents text,
  media text,
  order_id integer,
  action_applicable_days integer,
  preauth_enable boolean
);

DROP TABLE IF EXISTS dmart_mp.t_hem_hospital CASCADE;
CREATE TABLE dmart_mp.t_hem_hospital (
  id_pk bigserial PRIMARY KEY,
  hosp_id integer,
  hfr_hosp_id text,
  hosp_name text,
  hosp_address text,
  hosp_city text,
  hosp_pin integer,
  state_cd smallint,
  dist_cd smallint,
  hosp_mobile_no bigint,
  hosp_email_id text,
  hosp_contact_no text,
  hosp_website text,
  hosp_rating smallint,
  hosp_type_cd text,
  hosp_empnl_type text,
  hosp_longitude text,
  hosp_latitude text,
  hosp_gstin text,
  json_obj_hosp_dtl text,
  active_status integer,
  enrl_status integer,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  nodal_officer_name text,
  facility_id text,
  nodal_officer_number bigint,
  type text,
  hfr_facility_id text,
  hosp_spec_type text,
  upgrade_status integer,
  cluster_id integer,
  deempanel_status integer,
  u_role text,
  group_id text,
  pgdnb_status text,
  nodal_officer_email text,
  company_name text,
  cin_number text,
  establishment_year text,
  entity_id integer,
  empaneled_date timestamptz,
  hosp_type_cd_sub1 text,
  bed_size integer,
  data_source text,
  certificate_expiry_date timestamptz,
  is_pv_required integer,
  audit_status integer,
  hbp_hospital_id text,
  old_hosp_id text,
  query_allowed integer
);

DROP TABLE IF EXISTS dmart_mp.t_hem_sch_mapping CASCADE;
CREATE TABLE dmart_mp.t_hem_sch_mapping (
  id_pk bigserial PRIMARY KEY,
  hosp_id integer,
  scheme_code text,
  scheme_name text,
  active_status smallint,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  app_status integer,
  data_source text
);

DROP TABLE IF EXISTS dmart_mp.t_patient_dtl CASCADE;
CREATE TABLE dmart_mp.t_patient_dtl (
  state_code smallint,
  district_code smallint,
  is_authenticated smallint,
  registration_id text,
  name text,
  registration_date timestamptz,
  authentication_type text
);

DROP TABLE IF EXISTS dmart_mp.t_patient_dtls CASCADE;
CREATE TABLE dmart_mp.t_patient_dtls (
  id_pk bigserial PRIMARY KEY,
  registration_id text,
  careplan_id integer,
  program_id text,
  state_code smallint,
  district_code smallint,
  name text,
  dob text,
  gender text,
  registration_date timestamptz,
  hospital_id integer,
  hospital_name text,
  status_id smallint,
  referral_id text,
  ref_object_datavault text,
  ip_op text,
  consent_data smallint,
  member_type text,
  amount numeric,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  case_id text,
  hist_created_by text,
  hist_created_dt timestamptz,
  json_object_registration text,
  json_object_preauthorisation text,
  json_object_claim text,
  remarks text,
  is_authenticated smallint,
  authentication_type text,
  authentication_value text,
  admission_type text,
  admission_dt timestamptz,
  surgery_dt timestamptz,
  discharge_dt timestamptz,
  m_flag smallint,
  reason_code text,
  renewal_id integer,
  family_id text,
  discharge_type text,
  discharge_sub_type text,
  death_dt timestamptz,
  stage text,
  datalake_scheduler_flag text,
  payer_name text,
  renewal_code text,
  hosp_bill_number text,
  ben_type text,
  portability text,
  hosp_careplan_id integer,
  hosp_renewal_id integer,
  state_transition_flag text,
  table_name text
);

DROP TABLE IF EXISTS dmart_mp.t_payment_dtls CASCADE;
CREATE TABLE dmart_mp.t_payment_dtls (
  id_pk bigserial PRIMARY KEY,
  case_id text,
  payment_tran_type text,
  payment_type text,
  payment_unique_id text,
  payment_sequence_id text,
  careplan_id integer,
  src_bank_id text,
  src_account_no text,
  src_ifsc_code text,
  ben_bank_id text,
  ben_account_no text,
  ben_ifsc_code text,
  ben_account_name text,
  ben_mail_id text,
  ben_account_address text,
  ben_provider_type text,
  ben_provider_id text,
  transaction_amount numeric,
  bank_transaction_type text,
  transaction_date timestamptz,
  upload_file_name text,
  upload_file_path text,
  payment_sent_dt timestamptz,
  reject_code text,
  reject_flag text,
  reject_remarks text,
  payment_reject_dt timestamptz,
  paid_flag text,
  payment_paid_dt timestamptz,
  paid_remarks text,
  ack_flag text,
  ack_dt timestamptz,
  scheduler_flag text,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  ben_bank_branch text,
  src_bank_name text,
  registration_id text,
  case_no text,
  re_init_flag text,
  state_code text
);

DROP TABLE IF EXISTS dmart_mp.t_workflow_transaction_audit_hem CASCADE;
CREATE TABLE dmart_mp.t_workflow_transaction_audit_hem (
  id_pk bigserial PRIMARY KEY,
  work_id_pk bigint,
  workflow_transaction_id bigint,
  status_id numeric,
  service_request_type text,
  json_object text,
  workflow_process_code text,
  remarks text,
  criteria_code text,
  workflow_id text,
  previous_workflow_role text,
  acted_workflow_user text,
  version text,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  hist_created_by text,
  hist_created_dt timestamptz,
  final_level smallint,
  cluster_id integer,
  latest_rejection smallint,
  active_flag smallint,
  physical_report text,
  attachment text,
  transaction_dt timestamptz,
  admission_type text,
  scheme_code text
);

DROP TABLE IF EXISTS dmart_mp.tms_recovery CASCADE;
CREATE TABLE dmart_mp.tms_recovery (
  hosp_disp_code text,
  case_id text,
  requested_recovery_amount bigint,
  reason text,
  remarks text,
  created_dt timestamptz,
  tobe_recovered_amt bigint,
  recovered_case_id text,
  recovered_amt bigint,
  recovery_date timestamptz,
  recovery_status text,
  payer_id text,
  state_code bigint,
  state_name text
);

DROP TABLE IF EXISTS dmart_mp.treatment_dtls CASCADE;
CREATE TABLE dmart_mp.treatment_dtls (
  registration_id text,
  caseid text,
  item_id text,
  type text,
  type_desc text,
  date_on_which text,
  procedure_id text,
  procedure_code text,
  procedure_name text,
  procedure_strat text,
  procedure_strat_name text,
  stratification_amount text,
  procedure_type text,
  amount text,
  factor text,
  approved_factor text,
  no_of_days bigint,
  quantity bigint,
  approved_quantity bigint,
  unit_price numeric,
  net_amount numeric,
  approved_amount numeric,
  status text,
  remarks text,
  reason_code text,
  procedure_category_flag text,
  product_service text
);

-- Views

CREATE OR REPLACE VIEW dmart_mp.claim_paid_t AS SELECT * FROM dmart_mp.claim_paid_excel_t;

-- VIEW ump_users_v: create when source tables populated
-- CREATE OR REPLACE VIEW dmart_mp.ump_users_v AS SELECT ...;

CREATE INDEX IF NOT EXISTS idx_claim_port_case ON dmart_mp.claim_paid_t_portability (case_id);
CREATE INDEX IF NOT EXISTS idx_patient_dtls_case ON dmart_mp.t_patient_dtls (case_id);
CREATE INDEX IF NOT EXISTS idx_card_print_dist ON dmart_mp.t_card_printing_status (district_name);
CREATE INDEX IF NOT EXISTS idx_lms_user ON dmart_mp.lms_user_course_completion_status (userid);
CREATE INDEX IF NOT EXISTS idx_hosp_qual_facility ON dmart_mp.hospital_master_with_quality_certification_final (facility_id);
