-- MORTH / eDAR accident patient registry (Result 18.csv column names kept as-is).
CREATE TABLE IF NOT EXISTS dmart_mp.t_morth_patient_details (
  id_pk bigint PRIMARY KEY,
  addmission_type text,
  govt_id_type text,
  govt_id text,
  name text,
  age integer,
  gender text,
  father_spouce_name text,
  identity_mark text,
  pincode text,
  state text,
  district text,
  town text,
  address_1 text,
  address_2 text,
  mobile_number text,
  location_of_accident text,
  date_of_accident text,
  time_of_accident text,
  collision_type text,
  collision_nature text,
  details_of_injury text,
  ambulance_vehicle_number text,
  accident_severity text,
  no_of_vehicle integer,
  care_plan text,
  patient_brought_by text,
  brought_by_fullname text,
  brought_by_relation text,
  brought_by_mobile text,
  json_capture_photo text,
  patient_registration_id text,
  patient_con_uncon text,
  edar_victim_id text,
  hospital_id bigint,
  hospital_name text,
  hospital_address text,
  is_pushed_to_edhar text,
  edar_update_time timestamptz,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  is_victim_id_exist text,
  cause_of_accident text,
  victim_id_updated_dt_by_edar timestamptz,
  victim_id_remark_by_edar text,
  victim_id_approval_flag_by_edar text,
  hospital_state_code text,
  hospital_district_code text,
  pid text,
  district_of_accident text,
  district_name_of_accident text,
  state_of_accident text,
  state_name_of_accident text,
  responded_district_of_accident text,
  responded_state_of_accident text,
  life_threatening text,
  accident_brought_to_hospital text,
  landmark text,
  brought_by_ambulance text,
  attachment_content text,
  request_json text
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_morth_patient_reg
  ON dmart_mp.t_morth_patient_details (patient_registration_id)
  WHERE patient_registration_id IS NOT NULL AND btrim(patient_registration_id) <> '';
