-- Tables from PMJAY_dmart_mp_Schema_Reference.docx (14 tables)
-- Schema: dmart_mp
CREATE SCHEMA IF NOT EXISTS dmart_mp;

CREATE TABLE IF NOT EXISTS dmart_mp.already_printed_card_no_290626 (
  card_no text
);

CREATE TABLE IF NOT EXISTS dmart_mp.already_printed_card_no_34321992_8672488_09082026 (
  card_no text
);

CREATE TABLE IF NOT EXISTS dmart_mp.card_print_data_madhya_pradesh_01aug2025 (
  id_pk bigint PRIMARY KEY,
  card_no text,
  source_name text,
  kyc_name text,
  source_gender text,
  kyc_gender text,
  source_dob text,
  kyc_dob text,
  family_id text,
  member_id text,
  source_type text,
  father_name text,
  state_cd text,
  state_name text,
  dist_cd text,
  dist_name text,
  block_id text,
  block_name text,
  village_id text,
  village_name text,
  pincode text,
  rural_urban_flag text,
  abha_id text,
  ben_ref_id text,
  created_by text,
  created_dt timestamptz,
  approve_date timestamptz,
  card_status text,
  address text,
  photo text
);

CREATE TABLE IF NOT EXISTS dmart_mp.card_print_data_madhya_pradesh_vvs_29may2025_f (
  id_pk bigint PRIMARY KEY,
  card_no text,
  source_name text,
  kyc_name text,
  source_gender text,
  kyc_gender text,
  source_dob text,
  kyc_dob text,
  family_id text,
  member_id text,
  source_type text,
  father_name text,
  state_cd text,
  state_name text,
  dist_cd text,
  dist_name text,
  block_id text,
  block_name text,
  village_id text,
  village_name text,
  pincode text,
  rural_urban_flag text,
  abha_id text,
  ben_ref_id text,
  created_by text,
  created_dt timestamptz,
  approve_date timestamptz,
  card_status text,
  address text,
  photo text
);

CREATE TABLE IF NOT EXISTS dmart_mp.card_print_data_temp_t_bis_ekyc_dtl_mp_20260703_with_village_na (
  id_pk bigint PRIMARY KEY,
  card_no text,
  source_name text,
  kyc_name text,
  source_gender text,
  kyc_gender text,
  source_dob text,
  kyc_dob text,
  family_id text,
  member_id text,
  source_type text,
  ben_mobile_no text,
  father_name text,
  state_cd text,
  state_name text,
  dist_cd text,
  dist_name text,
  block_id text,
  block_name text,
  village_id text,
  village_name text,
  pincode text,
  rural_urban_flag text,
  abha_id text,
  ben_ref_id text,
  created_by text,
  created_dt timestamptz,
  approve_date timestamptz,
  card_status text,
  address text,
  photo text
);

CREATE TABLE IF NOT EXISTS dmart_mp.left_over_cards_for_print_of_mp_with_village_name_09aug2026_fin (
  id_pk bigint PRIMARY KEY,
  card_no text,
  source_name text,
  kyc_name text,
  source_gender text,
  kyc_gender text,
  source_dob text,
  kyc_dob text,
  family_id text,
  member_id text,
  source_type text,
  ben_mobile_no text,
  father_name text,
  state_cd text,
  state_name text,
  dist_cd text,
  dist_name text,
  block_id text,
  block_name text,
  village_id text,
  village_name text,
  pincode text,
  rural_urban_flag text,
  abha_id text,
  ben_ref_id text,
  created_by text,
  created_dt timestamptz,
  approve_date timestamptz,
  card_status text,
  address text,
  photo text
);

CREATE TABLE IF NOT EXISTS dmart_mp.pvtg_by_district_7march_v3 (
  familyid text,
  memberid text,
  name text,
  villege_name text,
  address text,
  card_no text,
  creationdate text,
  to_be_deleted text,
  dlt_reason text,
  verification_status text,
  sha_final_remark text,
  sha_final_action text
);

CREATE TABLE IF NOT EXISTS dmart_mp.t_beneficiary_ekyc_dtls_17july2025_old (
  id_pk bigint PRIMARY KEY,
  family_id text,
  member_id text,
  aadhaar_no text,
  status text,
  name text,
  yearofbirth text,
  gender text,
  photo text,
  fathername text,
  spouse text,
  mothername text,
  addressline1 text,
  addressline2 text,
  city text,
  district text,
  state text,
  pincode text,
  json_obj_ben_ekyc_dtl text,
  source_type text,
  plain_aadhaar text,
  card_no text,
  card_status text,
  mobile_no text,
  district_lgd text
);

CREATE TABLE IF NOT EXISTS dmart_mp.t_bis_beneficiary_disabled_19aug2025 (
  state_cd text,
  card_no text,
  card_status text,
  family_id text,
  member_id text,
  source_type text,
  name text,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  date_of_birth text,
  acted_workflow_user text,
  sha_user text,
  user_id text,
  sha_name text,
  email_id text,
  mobile_number bigint,
  entity_name text,
  role_name text,
  disabled_date timestamptz,
  reason_desc text,
  reason_id text
);

CREATE TABLE IF NOT EXISTS dmart_mp.m_status_bis (
  id_pk integer PRIMARY KEY,
  status smallint,
  status_descrption text,
  user_role text,
  action text,
  workflow_id text,
  status_name text,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz
);

CREATE TABLE IF NOT EXISTS dmart_mp.m_status_tms (
  id_pk integer PRIMARY KEY,
  status_descrption text,
  status smallint,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  user_role text,
  action text,
  workflow_id text,
  status_name text,
  search_status smallint
);

CREATE TABLE IF NOT EXISTS dmart_mp.t_hem_manpower (
  manpower_id_pk bigint PRIMARY KEY,
  med_exp_type text,
  exp_type text,
  name text,
  reg_number text,
  mobile_num text,
  emailid text,
  experience text,
  highest_qualification text,
  specialization text,
  university text,
  facility_opr_status text,
  json_obj_dtl text,
  ownership_type text,
  created_by text,
  created_dt timestamptz,
  updated_by text,
  updated_dt timestamptz,
  active_status smallint,
  hosp_id_pk integer,
  registration_certicate text,
  declaration_certificate text,
  shift text,
  manpower_type text,
  app_status integer,
  scheme_code text,
  hprid text,
  hrsubtype integer,
  data_source text,
  employment_type text
);

CREATE TABLE IF NOT EXISTS dmart_mp.json_data (
  id bigint PRIMARY KEY,
  registration_id integer,
  jsonb_value text,
  patientnumber text,
  householdid text,
  claimedamount numeric,
  totalamount numeric,
  approvedamount numeric,
  procedurestrat text,
  procedurestratname text,
  stratificationcost numeric,
  sno text,
  itemsequence integer,
  itemid text,
  packagecode text,
  packagetype text,
  packagecost numeric,
  procedurecost numeric,
  quantity numeric,
  approvedquantity numeric,
  percentageguidelines text,
  hospitalincentives text,
  incentivecategory text,
  amount numeric,
  netamount numeric,
  packagedesc text,
  status text,
  actionid text,
  actionname text,
  recoveryfunctionalityapplicable text,
  recoverydetails text,
  netpayable numeric,
  tdsdeduction numeric,
  rfdeduction numeric,
  gcamount numeric,
  gcpayableamount numeric,
  gctdsdeduction numeric,
  gcrfdeduction numeric,
  exempttype text,
  liabilitycode text,
  walletcode text,
  balanceamount numeric,
  liability_amount numeric,
  liability_approvedamount numeric
);

CREATE TABLE IF NOT EXISTS dmart_mp.treatment_stratification_details (
  registration_id integer,
  patientnumber text,
  householdid text,
  treatment_sno text,
  treatment_itemsequence integer,
  treatment_itemid text,
  type text,
  typedesc text,
  dateonwhich timestamptz,
  procedureid text,
  procedurecode text,
  procedurename text,
  proceduretype text,
  procedurecategoryflag text,
  procedurestrat text,
  procedurestratname text,
  stratamount numeric
);

